#!/usr/bin/python

from PIL import Image
import sys

ASCII_CHARS = "@%#*+=-:. "

def resize_image(image, new_width=100):
    width, height = image.size
    ratio = height / width / 1.65
    new_height = int(new_width * ratio)
    return image.resize((new_width, new_height))

def grayify(image):
    return image.convert("L")

def pixels_to_ascii(image):
    pixels = image.getdata()
    return "".join(ASCII_CHARS[pixel // 25] for pixel in pixels)

def image_to_ascii(path, new_width=100):
    image = Image.open(path)

    image = resize_image(image, new_width)
    image = grayify(image)

    ascii_str = pixels_to_ascii(image)

    w = image.width
    return "\n".join(ascii_str[i:i+w] for i in range(0, len(ascii_str), w))

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("使い方: aa <image> [width]")
        sys.exit(1)

    path = sys.argv[1]
    width = int(sys.argv[2]) if len(sys.argv) > 2 else 120

    print(image_to_ascii(path, width))
